name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set repository name to lowercase
        run: |
          echo "REPO_LOWER=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV
          echo "REPO_LOWER=${GITHUB_REPOSITORY,,}"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ env.REPO_LOWER }}/my-python-app:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ env.REPO_LOWER }}/my-python-app:${{ github.sha }}

      - name: Push Docker image with latest tag
        run: |
          docker tag ghcr.io/${{ env.REPO_LOWER }}/my-python-app:${{ github.sha }} ghcr.io/${{ env.REPO_LOWER }}/my-python-app:latest
          docker push ghcr.io/${{ env.REPO_LOWER }}/my-python-app:latest
