name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: debian-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/my-python-app:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}/my-python-app:${{ github.sha }}

      - name: Push Docker image with latest tag
        run: |
          docker tag ghcr.io/${{ github.repository }}/my-python-app:${{ github.sha }} ghcr.io/${{ github.repository }}/my-python-app:latest
          docker push ghcr.io/${{ github.repository }}/my-python-app:latest
